Feat/typescript
Team-Fruit/VCBot pull request #19
Opened 2021-01-03 10:54 UTC by kokoa0429

2021-01-03 11:08 UTC, sousuke0422 requested changes

2021-01-03 11:08 UTC, sousuke0422 commented on tsconfig.json
> +    "outDir": "./build",                        /* Redirect output structure to the directory. */
ここを`built`にするかpackage.jsonの`"start": "node ./built",`を修正しないと`npm run start`がまわらない

2021-01-03 11:12 UTC, kokoa0429 commented on tsconfig.json
> +    "outDir": "./build",                        /* Redirect output structure to the directory. */
なおした

2021-01-03 11:13 UTC, sousuke0422 approved these changes

2021-01-03 12:16 UTC, sousuke0422 commented
configとmp3のパス調整した？

2021-01-03 12:40 UTC, kokoa0429 commented
天才

2021-01-03 12:47 UTC, sousuke0422 commented
多分動くでしょ(適当)

2021-01-03 13:18 UTC, sousuke0422 commented
d6fcb52674b0f240c0dd7cbb0425299276c30e8f 90388d1493466e72d43f5ec4e3d58db7581efaae 1058eb981a576b960990c080e02e9a178f25d4d7 はrevertしないとだめかも(少なくとも d6fcb52674b0f240c0dd7cbb0425299276c30e8f  は必須？)

2021-01-04 04:55 UTC, yahho approved these changes

2021-01-06 15:47 UTC, merged